---
server:
    timezone: UTC
    locale: en_US.UTF-8
    local_hostname: 'ubuntu-trusty'
    local_fqdn_name: 'trusty.box'
    mail_address: 'matthias@colada.be'

nginx:
    docroot: /vagrant/web
    servername: trusty.box

php:
    ppa: php
    packages: [php5.6-cli, php5.6-intl, php5.6-mcrypt, php5.6-xml]
    pecl_packages: [mongo]

ufw:
    ssh: 22
    http: 80

